server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwt_security
    username: root
    password: rnrdj123


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true



logging:
  level:
    com.example.security: debug